# Generated by Django 2.2.1 on 2022-03-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task1',
            new_name='Qaz',
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='Qaz1',
        ),
        migrations.RenameModel(
            old_name='Task3',
            new_name='Qaz2',
        ),
        migrations.RenameModel(
            old_name='Task2',
            new_name='Qaz3',
        ),
    ]
