# Generated by Django 2.2.1 on 2022-03-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainer', '0002_auto_20220304_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qaz',
            old_name='title',
            new_name='cities',
        ),
        migrations.RenameField(
            model_name='qaz1',
            old_name='title',
            new_name='cities1',
        ),
        migrations.RenameField(
            model_name='qaz2',
            old_name='title',
            new_name='cities2',
        ),
        migrations.RenameField(
            model_name='qaz3',
            old_name='title',
            new_name='cities3',
        ),
    ]
