# Generated by Django 2.2.1 on 2022-03-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainer', '0005_auto_20220304_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('content1', models.TextField(verbose_name='Content')),
                ('stars', models.TextField(verbose_name='Stars')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messengers', models.CharField(max_length=50, verbose_name='Name')),
                ('experience', models.TextField(verbose_name='Description')),
                ('comment', models.TextField(verbose_name='Comments')),
            ],
        ),
        migrations.DeleteModel(
            name='Qaz1',
        ),
        migrations.DeleteModel(
            name='Qaz2',
        ),
        migrations.DeleteModel(
            name='Qaz3',
        ),
        migrations.AlterField(
            model_name='qaz',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
