# Generated by Django 2.2.1 on 2022-03-05 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainer', '0007_qaz3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='messengers',
            new_name='name_travel',
        ),
    ]
