# Generated by Django 2.2.1 on 2022-03-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainer', '0008_auto_20220305_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='experience',
            field=models.TextField(verbose_name='Experience'),
        ),
    ]
