# Generated by Django 2.2.1 on 2022-03-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainer', '0010_auto_20220316_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Info',
        ),
    ]
