# Generated by Django 2.2.1 on 2022-03-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainer', '0012_auto_20220316_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=50, verbose_name='Name')),
                ('time', models.TextField(verbose_name='Content')),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Qaz',
        ),
        migrations.DeleteModel(
            name='Qaz3',
        ),
    ]
