# Generated by Django 2.2.1 on 2022-03-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainer', '0013_auto_20220317_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time',
            field=models.TextField(verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work',
            field=models.CharField(max_length=50, verbose_name='Work'),
        ),
    ]
