# Generated by Django 2.2.1 on 2022-04-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainer', '0015_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
