# Generated by Django 2.2.1 on 2022-04-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainer', '0018_auto_20220413_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=15)),
                ('patronymic', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('telnumber', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрация',
                'ordering': ['name', 'lastname'],
            },
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
