# Generated by Django 2.2.1 on 2022-04-21 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainer', '0020_auto_20220421_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='patronymic',
            new_name='city',
        ),
    ]
